- name: install and start nginx
  hots: frontend
  tasks:
   - name: install nginx
     ansible.builtin.package:
     name: nginx
     state: present

   - name: state nginx
     ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes


  

 