- name: conditions
  hosts: local
  connection: local
  vars: 
    number: 15
  tasks:
  - name: check number is less than 10 or not
    ansible.builtin.debug:
      msg: "Given number {{ number }} is less than 10"
    when: number < 10

    # condiotns is valid, the result will print
    # condtions in not matched it will skip
    